# Generated by Django 3.1.1 on 2020-09-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('number_of_players', models.IntegerField()),
                ('joined_players', models.IntegerField()),
                ('player_current_turn', models.IntegerField()),
                ('player_last_turn', models.IntegerField()),
                ('current_card', models.IntegerField()),
                ('last_card', models.IntegerField()),
                ('stacked_cards', models.CharField(max_length=300)),
                ('last_amount_played', models.IntegerField()),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dubitoapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='CardsInHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_seed', models.CharField(max_length=1)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dubitoapp.player')),
            ],
        ),
    ]
