# Generated by Django 3.1.1 on 2020-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_current_turn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_last_turn',
            field=models.IntegerField(null=True),
        ),
    ]
