# Generated by Django 3.1.1 on 2020-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0002_auto_20200912_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_amount_played',
            field=models.IntegerField(null=True),
        ),
    ]
