# Generated by Django 3.1.1 on 2020-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0003_auto_20200912_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='joined_players',
            field=models.IntegerField(default=1),
        ),
    ]
