# Generated by Django 3.1.1 on 2020-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0005_player_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_begun',
            field=models.BooleanField(default=False),
        ),
    ]
