# Generated by Django 3.1.1 on 2020-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0007_auto_20200917_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
