# Generated by Django 3.1.1 on 2020-09-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0008_player_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_amount_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_last_turn',
            field=models.IntegerField(default=-1),
        ),
    ]
