# Generated by Django 3.1.4 on 2020-12-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0009_auto_20200923_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stacked_cards',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
