# Generated by Django 3.1.4 on 2021-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0010_auto_20201206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
