# Generated by Django 3.1.4 on 2021-01-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0013_auto_20210104_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='sender_name',
        ),
    ]
