# Generated by Django 3.1.4 on 2021-01-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0016_game_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
