# Generated by Django 3.1.4 on 2021-01-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0017_auto_20210107_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rejoined',
            field=models.BooleanField(default=True),
        ),
    ]
