# Generated by Django 3.1.4 on 2021-01-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0018_player_rejoined'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='restarted',
            field=models.IntegerField(default=0),
        ),
    ]
