# Generated by Django 3.1.4 on 2021-01-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0019_auto_20210115_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dubitoapp.game'),
        ),
    ]
