# Generated by Django 3.1.4 on 2021-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0020_auto_20210115_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_users', models.IntegerField(default=0)),
            ],
        ),
    ]
