# Generated by Django 3.1.4 on 2021-01-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0021_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coutdown_end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
