# Generated by Django 4.2.7 on 2023-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0023_alter_info_online_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stacked_cards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
