# Generated by Django 4.2.7 on 2023-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubitoapp', '0026_remove_player_game_id_player_game_player_is_ai_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'player_number'), name='player_unique_number'),
        ),
    ]
